Notless/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Notless.Models
{
    public class Cart
    {
        [Key]
        public int RecordID             { get; set; }
        public string CartID            { get; internal set; }
        public int ProductID            { get; set; }
        public int Count                { get; set; }
        public DateTime DateCreated     { get; set; }
        public virtual Product Product  { get; set; }
    }
}

Notless/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Notless.Models;

namespace Notless.Controllers
{
    public class OrderController : Controller
    {
        private RedStoreContext db = new RedStoreContext();

        // GET: Order
        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.Product).Include(o => o.User);
            return View(orders.ToList());
        }

        // GET: Order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductName");
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName");
            return View();
        }

        // POST: Order/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderID,TrackingNumber,OrderQty,UnitPrice,OrderDate,Total,ProductID,UserID")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductName", order.ProductID);
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName", order.UserID);
            return View(order);
        }

        // GET: Order/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductName", order.ProductID);
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName", order.UserID);
            return View(order);
        }

        // POST: Order/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderID,TrackingNumber,OrderQty,UnitPrice,OrderDate,Total,ProductID,UserID")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductName", order.ProductID);
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName", order.UserID);
            return View(order);
        }

        // GET: Order/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Notless/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using Notless.Models;

namespace Notless.Controllers
{
    public class OrdersController : ApiController
    {
        private RedStoreContext db = new RedStoreContext();

        // GET: api/Orders
        public IQueryable<Order> GetOrders()
        {
            return db.Orders;
        }

        // GET: api/Orders/5
        [ResponseType(typeof(Order))]
        public async Task<IHttpActionResult> GetOrder(int id)
        {
            Order order = await db.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }

            return Ok(order);
        }

        // PUT: api/Orders/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutOrder(int id, Order order)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != order.OrderID)
            {
                return BadRequest();
            }

            db.Entry(order).State = EntityState.Modified;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrderExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Orders
        [ResponseType(typeof(Order))]
        public async Task<IHttpActionResult> PostOrder(Order order)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Orders.Add(order);
            await db.SaveChangesAsync();
            
            return CreatedAtRoute("DefaultApi", new { id = order.OrderID }, order);
        }

        // DELETE: api/Orders/5
        [ResponseType(typeof(Order))]
        public async Task<IHttpActionResult> DeleteOrder(int id)
        {
            Order order = await db.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }

            db.Orders.Remove(order);
            await db.SaveChangesAsync();

            return Ok(order);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool OrderExists(int id)
        {
            return db.Orders.Count(e => e.OrderID == id) > 0;
        }
    }
}

Notless/Controllers/ShoppingCartController.cs
using Notless.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Security;

namespace Notless.Controllers
{
    public class ShoppingCartController : Controller
    {
        RedStoreContext storeDB = new RedStoreContext();
        private string CartID;
        List<Cart> list = new List<Cart>();
        
        // GET: ShoppingCart
        [HttpGet]
        public ActionResult Index()
        {
            //ViewBag.listProducts = storeDB.Products.ToList();
            //storeDB.Products.ToList()
            if (Session["UserID"] != null)
            {
                CartID = Session["UserID"].ToString();
                if (Session["CartID"] == null)
                {
                    Session["CartID"] = CartID;
                }
                foreach (var item in storeDB.Carts.Where(c => c.CartID == CartID).ToList())
                {
                    list.Add(item);
                }
            }
            else
            {
                if (Session["CartID"] == null)
                {
                    CartID = new Guid().ToString();
                    Session["CartID"] = CartID;
                }
                list = Session["listCart"]!= null? (List<Cart>)Session["listCart"] : list;
            }
            Session["listCart"] = list;
            return View(list);
        }

        
        public ActionResult Del(int id)
        {
            list = (List<Cart>)Session["listCart"];
            if(list != null)
            {
                list.RemoveAt(IndLst(id));
                if(Session["UserID"] != null)
                try
                {
                    var cart = Session["UserID"].ToString();
                    storeDB.Carts.Remove(storeDB.Carts.SingleOrDefault(c => c.ProductID == id && c.CartID == cart));
                    storeDB.SaveChanges();
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "Error in db.";
                }
            }
            
            Session["listCart"] = list;

            return View("Index",list);
        }
        

        // GET: /Store/AddToCart/5
        [HttpGet]
        public ActionResult AddToCart(int id)
        {
            // Retrieve the product from the database
            var addProduct = storeDB.Products.Find(id);

            if (Session["UserID"] == null)
            {
                if (Session["CartID"] == null)
                {
                    CartID = new Guid().ToString();
                    Session["CartID"] = CartID;
                }
            }
            else
            {
                Session["CartID"] = Session["UserID"];
                CartID = Session["UserID"].ToString();
                if (IndLst(id) == -1)
                    storeDB.Carts.Add(new Cart { CartID = Session["CartID"].ToString(), Count = 1, DateCreated = DateTime.Now, Product = addProduct, ProductID = addProduct.ProductID });
                else
                {
                    var c = storeDB.Carts.SingleOrDefault(p => p.ProductID == id);
                    if (c != null) c.Count++;
                }
                storeDB.SaveChanges();
            }
            
            if (Session["listCart"] == null)
            {
                if (Session["UserID"] != null) Session["CartID"] = Session["UserID"];
                list.Add(new Cart { CartID = Session["CartID"].ToString(), Count = 1, DateCreated = DateTime.Now, Product = addProduct, ProductID = addProduct.ProductID });
            }
            else
            {
                list = (List<Cart>)Session["listCart"];

                if (IndLst(id) == -1)
                    list.Add(new Cart { CartID = Session["CartID"].ToString(), Count = 1, DateCreated = DateTime.Now, Product = addProduct, ProductID = addProduct.ProductID });
                else
                    list[IndLst(id)].Count++;
            }

            Session["listCart"] = list;

            return RedirectToAction("Index", list);
        }

        private int IndLst(int id)
        {
            
            //list = (List<Cart>)Session["listCart"];
            if(Session["listCart"] != null || list != null)
            foreach (var item in list)
            {
                if (item.ProductID == id)
                    return list.IndexOf(item);
            }
            return -1;
        }

        [HttpGet]
        public ActionResult Order()
        {
            if (Session["UserID"] != null)
            {
                var id = Convert.ToInt32(Session["UserID"]);
                    var ord = storeDB.Orders.Where(o => o.UserID == id).ToList();
                    if(ord != null)
                        return View(ord);
            }
            
            return RedirectToAction("Login", "User", "");
        }

        
        public ActionResult PlaceOrder(int? id)
        {
            if (Session["UserID"] != null && list != null)
            {
                var usr = Session["UserID"].ToString();
                list = storeDB.Carts.Where(c => c.CartID == usr).ToList();
                try
                {
                    foreach (var item in list)
                    {
                        storeDB.Orders.Add(new Order
                        {
                            OrderDate = DateTime.Now,
                            OrderQty = item.Count,
                            Product = item.Product,
                            ProductID = item.ProductID,
                            UnitPrice = item.Product.UnitPrice,
                            UserID = Convert.ToInt32(Session["UserID"]),
                            Total = item.Count * item.Product.UnitPrice
                        });

                            try
                            {
                                storeDB.Carts.Remove(storeDB.Carts.SingleOrDefault(c => c.ProductID == item.ProductID && c.CartID == usr));
                            }
                            catch (Exception ex)
                            {
                                ViewBag.Message = "Error in db.";
                            }


                        storeDB.SaveChanges();
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "Error to acces db.";
                }

            }
            else
            {
                return RedirectToAction("Login", "User", "");
            }
            return RedirectToAction("Order");
        }


        public ActionResult Cancel(int id)
        {

            var usr = Convert.ToInt32(Session["UserID"]);

            try
            {
                var cart = usr.ToString();
                storeDB.Orders.Remove(storeDB.Orders.SingleOrDefault(c => c.OrderID == id && c.UserID == usr));
                storeDB.SaveChanges();
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Error in db.";
            }

            var ord = storeDB.Orders.Where(o => o.UserID == usr).ToList();
            if (ord == null)
                return RedirectToAction("Order");

            return RedirectToAction("Order", ord);
        }

        public ActionResult Update(int id, int count)
        {
            if(count > 0)
            {
                if((List<Cart>)Session["listCart"] != null)
                    list = (List<Cart>)Session["listCart"];
                foreach (var item in list)
                {
                    if (item.ProductID == id)
                    {
                        item.Count = count;
                        if(Session["UserID"] != null)
                        {
                            var usr = Session["UserID"].ToString();
                            storeDB.Carts.Where(c => c.ProductID == id && c.CartID == usr).FirstOrDefault().Count = count;
                            storeDB.SaveChanges();
                        }
                    
                    }
                }
            }
            
            Session["listCart"] = list;
            return RedirectToAction("Index", list);
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            //var cart = ShoppingCart.GetCart(this.HttpContext);
            
            // Get the name of the album to display confirmation
            string Name = storeDB.Carts
                .Single(item => item.RecordID == id).Product.ProductName;

            // Remove from cart
            //int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            /*
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(Name) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            */
            return Json("");
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            //var cart = ShoppingCart.GetCart(this.HttpContext);

            //ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

Notless/Views/ShoppingCart/Cart.cshtml
@model IEnumerable<Notless.Models.Cart>

@{
    ViewBag.Title = "Cart";
}

<h2>Cart</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Count)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.ProductType.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.UnitPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.UnitMeasure)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(model => item.Product.ProductName)
        </td>
        <td>
            @Html.DisplayFor(model => item.Count)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.ProductType.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.UnitPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.UnitMeasure)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProductID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProductID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProductID })
        </td>
    </tr>
}

</table>

Notless/Views/ShoppingCart/Index.cshtml
@model IEnumerable<Notless.Models.Cart>
@using Notless.Models
@{
    ViewBag.Title = "Shopping Cart";
}

<h2>Cart</h2>

@if (Model.Count() > 0)
{ 


<table class="table" id="tblCarts">
    <tr class="alert-danger">@ViewBag.Message</tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Count)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.ProductType.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.UnitPrice)
        </th>
        <th>
            Total Price
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.UnitMeasure)
        </th>
        
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.Product.ProductName)
            </td>
            <td>
                @Html.TextBoxFor(model => item.Count, new { @class="form-control", size = "5", maxlength = "5", type = "number", id="count" + item.ProductID })
                
            </td>
            <td>
                @Html.DisplayFor(model => item.Product.ProductType.Name)
            </td>
            <td>
                @Html.DisplayFor(model => item.Product.UnitPrice)
            </td>
            <td>
                @(item.Product.UnitPrice * item.Count)
            </td>
            <td>
                @Html.DisplayFor(model => item.Product.UnitMeasure)
            </td>
            
            <td id="link">
                @Html.ActionLink("Update", "Update", new { id = item.ProductID, count = item.Count }, htmlAttributes: new { @class = "btn btn-default", id="count" + item.ProductID, @disabled = "disabled" }) |
                @Html.ActionLink("Details", "Details", "Product", new { id = item.ProductID }, htmlAttributes: new { @class = "btn btn-default" }) |
                @Html.ActionLink("Delete", "Del", "ShoppingCart", new { id = item.ProductID }, htmlAttributes: new { @class = "btn btn-default"})
            </td>
        </tr>
    }

</table>
 
}
else{
<p>You shopping cart is empty!</p>
}
<hr />
@Html.ActionLink("Continue shopping", "", "Product", null, htmlAttributes: new { @class = "btn btn-default" })
<span>&nbsp;</span>
@Html.ActionLink("Place order", "PlaceOrder", "ShoppingCart", new { id = Session["UserID"] }, htmlAttributes: new { @class = "btn btn-default" })
<span>&nbsp;</span>
@Html.ActionLink("My orders", "Order", "ShoppingCart", null, htmlAttributes: new { @class = "btn btn-default" })


@section Scripts{
        <script>

            /*
            $("input[id^='count']").change(function () {
                //var count = $("input[id^='count']").val();
                $("a[href^='/ShoppingCart/Update/']").attr('href', '/ShoppingCart/Update/' + '' + this.id + '?count=' + '96');

                
            });

            */

            $("input[id^='count']").change(function () {

                //alert($(this).val());

                var lord = $(this).val();
                //$("#tblCarts td#" + "link").find("a[href^='/ShoppingCart/Update/']").attr('href', '/ShoppingCart/Update/' + $(this).val());
                var $parent = $(this);

                $("a[href^='/ShoppingCart/Update/']").each(function () {

                    //alert($parent.attr("id"));
                    var $this = $(this);
                    var _href = $this.attr("href");

                    //alert($this.attr("id"));
                    if ($parent.attr("id") == $this.attr("id")) {
                        $(this).removeAttr('disabled');
                        $this.attr("href", _href.substring(0,31) + lord);
                    }
                    
                });

                //$("a[href^='/ShoppingCart/Update/']").attr('href', '/ShoppingCart/Update/' + '' + this.id + '?count=' + '96');
            });
                //$("a[href^='/ShoppingCart/Update/']").attr('href', '/ShoppingCart/Update/' + '' + '?count=' + count);
                //alert($("#update").attr("href"));
                
        </script>
    }



@if(Session["listCart"] == null)
{
<table>
    <tr>
        <th>Product Name</th>
        <th>Count</th>
        <th>ProductType</th>
        <th>Cost</th>
    </tr>
    @foreach (var item in (List<Cart>)Session["listCart"])
    {
        <tr>
            <td>@item.Product.ProductName</td>
            <td>@item.Count</td>
            <td>@item.Product.ProductType.Name</td>
            <td>@(item.Count * item.Product.UnitPrice)</td>
            <td>@Html.ActionLink("Delete", "Del", "ShoppingCart", new { id = item.ProductID },null)</td>
        </tr>
    }
</table>
}

Notless/Views/ShoppingCart/Order.cshtml
@model IEnumerable<Notless.Models.Order>

@{
    ViewBag.Title = "Order";
}

<h2>Order</h2>


@ViewBag.Message

@if(Model.Count() > 0 && Model.Any())
{ 
<table class="table col-lg-12">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </th>
      

        <th>
            @Html.DisplayNameFor(model => model.OrderQty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th></th>
    </tr>
    @{ 
        decimal TotalCost = 0;
    }

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Product.ProductName)
        </td>


        <td>
            @Html.DisplayFor(modelItem => item.OrderQty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            <!--@Html.ActionLink("Edit", "Edit", "Oder", new { id=item.OrderID }, null) |-->
            @Html.ActionLink("Details", "Details", "Order", new { id = item.OrderID }, null ) |
            @Html.ActionLink("Cancel", "Cancel", "ShoppingCart", new { id=item.OrderID }, htmlAttributes: new {  @class = "btn btn-default"})
        </td>
    </tr>

    TotalCost += item.Total;

}
    
    <tr>
        <td><hr /></td><td><hr /></td><td><hr /></td><td align="right"><hr /><b>Sum</b></td>
        <td><hr /><b>@TotalCost</b></td>
        <td><hr /><input type="button" title="Purchase" value="Purchase"  class="btn btn-success" /></td>
    </tr>

</table>
    
}
else
{
    <p>You don't have orders.</p>
}

Notless/Views/ShoppingCart/PlaceOrder.cshtml
@model IEnumerable<Notless.Models.Order>

@{
    ViewBag.Title = "PlaceOrder";
}

<h2>PlaceOrder</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TrackingNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderQty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Product.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TrackingNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderQty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.OrderID }) |
            @Html.ActionLink("Details", "Details", new { id=item.OrderID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.OrderID })
        </td>
    </tr>
}

</table>