Notless/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Notless.Controllers
{
    public class ItemsController : Controller
    {
        // GET: Items
        public ActionResult Index()
        {
            return View();
        }
    }
}

Notless/Controllers/UserController.cs
using Notless.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Session;
using Microsoft.AspNet.Http;
using System.Web.Security;
using System.Web.Configuration;
using System.Text;
using System.Security.Cryptography;
using System.Net.Mail;
using System.Net;
using System.Collections.Specialized;
using System.IO;
using System.Web.Script.Serialization;
using System.Data.Entity.Validation;

namespace Notless.Controllers
{
    public class MyObject
    {
        public string success { get; set; }
        public DateTime challenge_ts { get; set; }
        public string hostname { get; set; }
        public string[] error_codes { get; set; }

    }

    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            if (Session["Role"].ToString() == "3")
                return View();
            else
                return RedirectToAction("Dashboard");
        }

        public ActionResult Dashboard()
        {
            HttpCookie cookieU = Request.Cookies["UserName"];
            HttpCookie cookieR = Request.Cookies["Role"];

            if (Session["UserID"] != null)
            {
                
                using (RedStoreContext db = new RedStoreContext())
                {
                    int s = Convert.ToInt32(Session["UserID"]);
                    var usr = db.Users.Where(u => u.UserID == s).FirstOrDefault();
                    return View(usr);
                }
                
                //return View();
            }
            else if (cookieU != null && cookieR != null)
            {
                var u = cookieU.Value.ToString();
                RedStoreContext context = new RedStoreContext();
                var usr = context.Users.Where(x => x.UserName == u).FirstOrDefault();
                Session["UserID"] = usr.UserID;
                Session["Role"] = usr.RoleID;
                return View(usr);
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        public ActionResult Register()
        {
            ViewBag.Country = new SelectList(new List<string>{
                "Afghanistan", "Albania",
                "Algeria",     "Andorra",
                "Angola",      "Antigua and Barbuda",
                "Argentina",   "Armenia",
                "Aruba",       "Australia",
                "Austria",     "Azerbaijan",
                "Bahamas, The","Bahrain",
                "Bangladesh",  "Barbados",
                "Belarus",     "Belgium",
                "Belize",      "Benin",
                "Bhutan",      "Bolivia",
                "Bosnia and Herzegovina",
                "Botswana",    "Brazil",
                "Brunei",      "Bulgaria",
                "Burkina Faso","Burma",
                "Burundi",     "Cambodia",
                "Cameroon",    "Canada",
                "Cabo Verde",  "Central African Republic",
                "Chad",        "Chile",
                "China",       "Colombia",
                "Comoros",     "Congo, Democratic Republic of the",
                "Congo, Republic of the",
                "Costa Rica",  "Cote d'Ivoire",
                "Croatia",     "Cuba",
                "Curacao",
                "Cyprus",
                "Czechia",
                "Denmark",
                "Djibouti",
                "Dominica",
                "Dominican Republic",
                "East Timor (see Timor-Leste)",
                "Ecuador",
                "Egypt",
                "El Salvador",
                "Equatorial Guinea",
                "Eritrea",
                "Estonia",
                "Ethiopia",
                "Fiji",
                "Finland",
                "France",
                "Gabon",
                "Gambia, The",
                "Georgia",
                "Germany",
                "Ghana",
                "Greece",
                "Grenada",
                "Guatemala",
                "Guinea",
                "Guinea-Bissau",
                "Guyana",
                "Haiti",
                "Holy See",
                "Honduras",
                "Hong Kong",
                "Hungary",
                "Iceland",
                "India",
                "Indonesia",
                "Iran",
                "Iraq",
                "Ireland",
                "Israel",
                "Italy",
                "Jamaica",
                "Japan",
                "Jordan",
                "Kazakhstan",
                "Kenya",
                "Kiribati",
                "Korea, North",
                "Korea, South",
                "Kosovo",
                "Kuwait",
                "Kyrgyzstan",
                "Laos",
                "Latvia",
                "Lebanon",
                "Lesotho",
                "Liberia",
                "Libya",
                "Liechtenstein",
                "Lithuania",
                "Luxembourg",
                "Macau",
                "Macedonia",
                "Madagascar",
                "Malawi",
                "Malaysia",
                "Maldives",
                "Mali",
                "Malta",
                "Marshall Islands",
                "Mauritania",
                "Mauritius",
                "Mexico",
                "Micronesia",
                "Moldova",
                "Monaco",
                "Mongolia",
                "Montenegro",
                "Morocco",
                "Mozambique",
                "Namibia",
                "Nauru",
                "Nepal",
                "Netherlands",
                "New Zealand",
                "Nicaragua",
                "Niger",
                "Nigeria",
                "North Korea",
                "Norway",
                "Oman",
                "Pakistan",
                "Palau",
                "Palestinian Territories",
                "Panama",
                "Papua New Guinea",
                "Paraguay",
                "Peru",
                "Philippines",
                "Poland",
                "Portugal",
                "Qatar",
                "Romania",
                "Russia",
                "Rwanda",
                "Saint Kitts and Nevis",
                "Saint Lucia",
                "Saint Vincent and the Grenadines",
                "Samoa",
                "San Marino",
                "Sao Tome and Principe",
                "Saudi Arabia",
                "Senegal",
                "Serbia",
                "Seychelles",
                "Sierra Leone",
                "Singapore",
                "Sint Maarten",
                "Slovakia",
                "Slovenia",
                "Solomon Islands",
                "Somalia",
                "South Africa",
                "South Korea",
                "South Sudan",
                "Spain",
                "Sri Lanka",
                "Sudan",
                "Suriname",
                "Swaziland",
                "Sweden",
                "Switzerland",
                "Syria",
                "Taiwan",
                "Tajikistan",
                "Tanzania",
                "Thailand",
                "Timor-Leste",
                "Togo",
                "Tonga",
                "Trinidad and Tobago",
                "Tunisia",
                "Turkey",
                "Turkmenistan",
                "Tuvalu",
                "Uganda",
                "Ukraine",
                "United Arab Emirates",
                "United Kingdom",
                "Uruguay",
                "Uzbekistan",
                "Vanuatu",
                "Venezuela",
                "Vietnam",
                "Yemen",
                "Zambia",
                "Zimbabwe"
            }, "Country");
            return View();
        }

        static string Sha256(string randomString)
        {
            SHA256Managed crypt = new System.Security.Cryptography.SHA256Managed();
            StringBuilder hash = new System.Text.StringBuilder();
            byte[] crypto = crypt.ComputeHash(Encoding.UTF8.GetBytes(randomString), 0, Encoding.UTF8.GetByteCount(randomString));
            foreach (byte theByte in crypto)
            {
                hash.Append(theByte.ToString("x2"));
            }
            return hash.ToString();
        }


        public string CalculateMessageDigest(string originalMessage, HashAlgorithm hashAlgo)
        {
            return Convert.ToBase64String(hashAlgo.ComputeHash(Encoding.UTF8.GetBytes(originalMessage)));
        }

        [HttpPost]
        public ActionResult Register(User user)
        {
            user.RoleID = 1;

            if (user.Gender == "Gender")
            {
                ModelState.AddModelError("Gender", "Select gender.");
                return View();
            }

            if (ModelState.IsValid)
            {
                //ViewBag.Pass = Sha256(user.Password).ToString();
                user.Password = CalculateMessageDigest(user.Password, SHA512.Create());
                user.CreatedDate = DateTime.Now;
                
                using (RedStoreContext db = new RedStoreContext())
                {
                    if (db.Users.Where(u => u.UserName == user.UserName).FirstOrDefault() != null)
                    {
                        ModelState.AddModelError("UserName", "That username is already registered.");
                        return View();
                    }
                    else if (db.Users.Where(u => u.Email == user.Email).FirstOrDefault() != null)
                    {
                        ModelState.AddModelError("Email", "That email is already registered.");
                        return View();
                    }
                    else
                    {
                        user.LastName = user.LastName.Trim();
                        user.FirstName = user.FirstName.Trim();

Notless/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("REDStore", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Products", "Index", "Items", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Dashboard", "Dashboard", "User", new { area = "" }, null)</li>
                    <!--<li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>-->
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, null)</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">

        <div class="page-header">
            @if (Session["UserID"] == null)
            {
                @Html.ActionLink("Register", "Register", "User", new { area = "" }, htmlAttributes: new { @class = "btn btn-default" })
                <span>&nbsp;</span>
                @Html.ActionLink("Login", "Login", "User", new { area = "" }, htmlAttributes: new { @class = "btn btn-default" })
            }
            else
            {
                @Html.ActionLink("Profile", "Dashboard", "User", new { area = "" }, htmlAttributes: new { @class = "btn btn-default" })
                <span>&nbsp;</span>
                @Html.ActionLink("Logout", "Logout", "User", new { area = "" }, htmlAttributes: new { @class = "btn btn-default" })
            }

            <span>&nbsp;</span>
                @Html.ActionLink("Products", "", "Product", new { area = "" }, htmlAttributes: new { @class = "btn btn-default" })
                <span>&nbsp;</span>
                @Html.ActionLink("Shopping Cart", "", "ShoppingCart", new { area = "" }, htmlAttributes: new { @class = "btn btn-default" })    

        </div>

        @RenderBody()
        <hr />
        <footer>
            <p align="center">&copy; @DateTime.Now.Year - REDStore</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>